services:
  - type: web
    name: bazar-tafraout
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    region: frankfurt
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8
      - key: SECRET_KEY
        generateValue: true
      - key: ADMIN_PASSWORD
        value: Torino_2026
